// Copyright 2023 Savotina Valeria
#ifndef TASKS_TASK_2_SAVOTINA_V_SLEEPING_BARBER_SLEEPING_BARBER_H_
#define TASKS_TASK_2_SAVOTINA_V_SLEEPING_BARBER_SLEEPING_BARBER_H_

#include <mpi.h>

#endif  // TASKS_TASK_2_SAVOTINA_V_SLEEPING_BARBER_SLEEPING_BARBER_H_
