// Copyright 2023 Savotina Valeria
#ifndef TASKS_TASK_1_SAVOTINA_V_COUNT_SYM_IN_STR_COUNT_SYM_IN_STR_H_
#define TASKS_TASK_1_SAVOTINA_V_COUNT_SYM_IN_STR_COUNT_SYM_IN_STR_H_

#include <mpi.h>

#endif  // TASKS_TASK_1_SAVOTINA_V_COUNT_SYM_IN_STR_COUNT_SYM_IN_STR_H_
