// Copyright 2023 Ionova Ekaterina
#ifndef TASKS_TASK_2_IONOVA_E_SMOOTHING_FILTER_FILTER_H
#define TASKS_TASK_2_IONOVA_E_SMOOTHING_FILTER_FILTER_H

#include <mpi.h>

#endif  // TASKS_TASK_2_IONOVA_E_SMOOTHING_FILTER_FILTER_H
